/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_qlptgt_n10.view.user;

import btl_qlptgt_n10.view.admin.*;
import btl_qlptgt_n10.controller.XeTaiController;
import btl_qlptgt_n10.model.XeTai;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naman
 */
public class XeTaiManagement extends javax.swing.JFrame {

    /**
     * Creates new form transportationManagement
     */
    private void UpdateTable() throws SQLException {
        ArrayList<XeTai> xeTais = (ArrayList<XeTai>) xeTaiController.getAllXeTai();
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        for (int i = 0; i < xeTais.size(); i++) {
            XeTai xeTai = xeTais.get(i);
            defaultTableModel.addRow(new Object[]{
                i + 1,
                xeTai.getId(),
                "Xe tải",
                xeTai.getHangSanXuat(),
                xeTai.getNamSanXuat(),
                xeTai.getGiaBan(),
                xeTai.getMau(),
                xeTai.getTrongTai()
            });
        }
    }

    public XeTaiManagement() throws SQLException {
        initComponents();
        myInit();
        UpdateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboHangSanXuat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboNamSanXuat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboMau = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboSoChoNgoi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        txtDongCo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTrongTai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCongXuat = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhuongTien = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ PHƯƠNG TIỆN GIAO THÔNG");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ XE TẢI");

        jLabel3.setText("Hãng sản xuất:");

        cboHangSanXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vinfast", "Mercedes", "Honda", "Toyota", "Yamaha", "Suzuki", "Kia", "Huyndai", "Mazda", "Nissan", "Lexus", "Ford", "Porsche", "Bentley", "Audi", "Bugatti", "Ferrari", "Lamborghini", "BMW" }));

        jLabel4.setText("Năm sản xuất:");

        cboNamSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamSanXuatActionPerformed(evt);
            }
        });

        jLabel5.setText("Màu:");

        cboMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng", "Đen", "Đỏ", "Vàng", "Bạc", "Xanh Lá Cây", "Xanh Da Trời", "Tím", "Cam", "Hồng", "Nâu", "Xám" }));

        jLabel6.setText("Số chỗ ngồi:");

        cboSoChoNgoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "5", "7", "9", "12", "16", "24", "30", "45" }));

        jLabel7.setText("Giá bán:");

        txtDongCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDongCoActionPerformed(evt);
            }
        });

        jLabel8.setText("Kiểu động cơ:");

        jLabel9.setText("Trọng tải:");

        txtTrongTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrongTaiActionPerformed(evt);
            }
        });

        jLabel10.setText("Công xuất:");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jButton2.setText("Cập nhật");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Xóa dữ liệu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Xem danh sách");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton6)
                .addGap(65, 65, 65)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPhuongTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Id", "Loại phương tiện", "Hãng sản xuất", "Năm sản xuất", "Giá bán", "Màu", "Trọng tải"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhuongTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhuongTienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhuongTien);

        txtId.setEditable(false);

        jLabel11.setText("Id:");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton4.setText("Tìm kiếm theo hãng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Tìm kiếm theo màu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Tìm kiếm theo năm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Tìm kiếm theo giá bán");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Tìm kiếm theo trọng tải");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Lựa chọn");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_qlptgt_n10/view/icon/icons8-car-48.png"))); // NOI18N
        jMenuItem1.setText("Quản lý ô tô");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_qlptgt_n10/view/icon/icons8-motorcycle-48.png"))); // NOI18N
        jMenuItem2.setText("Quản lý xe máy");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_qlptgt_n10/view/icon/logout-icon-48.png"))); // NOI18N
        jMenuItem3.setText("Đóng");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboNamSanXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHangSanXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCongXuat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSoChoNgoi, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE)
                            .addComponent(txtDongCo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTrongTai))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtDongCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cboSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTrongTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cboHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cboNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNamSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamSanXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamSanXuatActionPerformed

    private void txtDongCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDongCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDongCoActionPerformed

    private void txtTrongTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrongTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrongTaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        cboHangSanXuat.setSelectedIndex(0);
        cboNamSanXuat.setSelectedIndex(0);
        txtGiaBan.setText("");
        cboMau.setSelectedIndex(0);
        txtDongCo.setText("");
        cboSoChoNgoi.setSelectedIndex(0);
        txtCongXuat.setText("");
        txtTrongTai.setText("");
        cboHangSanXuat.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtGiaBan.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Giá bán không được để trống", "Lỗi thêm mới", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtTrongTai.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Trọng tải không được để trống", "Lỗi thêm mới", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        XeTai xeTai = new XeTai(Float.parseFloat(txtTrongTai.getText()), cboHangSanXuat.getSelectedItem().toString(), Integer.parseInt(cboNamSanXuat.getSelectedItem().toString()), Float.parseFloat(txtGiaBan.getText()), cboMau.getSelectedItem().toString());
        if (!xeTaiController.createNewXeTai(xeTai)) {
            JOptionPane.showConfirmDialog(null, "Thêm phương tiện thất bại", "Lỗi thêm mới", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            UpdateTable();
        } catch (SQLException ex) {
            Logger.getLogger(XeTaiManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        OtoManagement otoManagement = null;
        try {
            otoManagement = new OtoManagement();
        } catch (SQLException ex) {
            Logger.getLogger(SelectTransportUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        otoManagement.setLocationRelativeTo(null);
        otoManagement.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SelectTransportUser selectTransport = new SelectTransportUser();
        selectTransport.setLocationRelativeTo(null);
        selectTransport.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void tblPhuongTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhuongTienMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tblPhuongTien.getModel();
        Vector<Object> courseVector = (Vector<Object>) tableModel.getDataVector().elementAt(tblPhuongTien.getSelectedRow());
        XeTai xeTai = new XeTai();
        xeTai.setId(Integer.parseInt(courseVector.get(1).toString()));
        xeTai.setHangSanXuat(courseVector.get(3).toString());
        xeTai.setNamSanXuat(Integer.parseInt(courseVector.get(4).toString()));
        xeTai.setGiaBan(Float.parseFloat(courseVector.get(5).toString()));
        xeTai.setMau(courseVector.get(6).toString());
        xeTai.setTrongTai(Float.parseFloat(courseVector.get(7).toString()));
        
        txtId.setText(String.valueOf(xeTai.getId()));
        cboHangSanXuat.getModel().setSelectedItem(xeTai.getHangSanXuat());
        cboNamSanXuat.getModel().setSelectedItem(xeTai.getNamSanXuat());
        txtGiaBan.setText(String.valueOf(xeTai.getGiaBan()));
        cboMau.getModel().setSelectedItem(xeTai.getMau());
        txtTrongTai.setText(String.valueOf(xeTai.getTrongTai()));
    }//GEN-LAST:event_tblPhuongTienMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtGiaBan.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Giá bán không được để trống", "Lỗi cập nhật", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtTrongTai.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Trọng tải không được để trống", "Lỗi cập nhật", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        XeTai xeTai = new XeTai(
                Float.parseFloat(txtTrongTai.getText()),
                Integer.parseInt(txtId.getText()),
                cboHangSanXuat.getSelectedItem().toString(),
                Integer.parseInt(cboNamSanXuat.getSelectedItem().toString()),
                Float.parseFloat(txtGiaBan.getText()),
                cboMau.getSelectedItem().toString()
        );
        
        if (!xeTaiController.updateXeTaiById(xeTai)) {
            JOptionPane.showConfirmDialog(null, "Sửa thông tin xe tải thất bại", "Sửa thông tin xe tải", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showConfirmDialog(null, "Sửa thông tin xe tải thành công", "Sửa thông tin xe tải", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        try {
            UpdateTable();
        } catch (SQLException ex) {
            Logger.getLogger(XeTaiManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Chưa chọn phương tiện cần xóa", "Xóa thông tin xe tải", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }

        int responseConfirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa không?", "Xóa thông tin xe tải", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (responseConfirm == JOptionPane.YES_OPTION) {
            if (!xeTaiController.deleteXeTaiById(Integer.parseInt(txtId.getText()))) {
                JOptionPane.showConfirmDialog(null, "Xóa thông tin xe tải thất bại", "Xóa thông tin xe tải", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showConfirmDialog(null, "Xóa thông tin xe tải thành công", "Xóa thông tin xe tải", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            try {
                UpdateTable();
            } catch (SQLException ex) {
                Logger.getLogger(XeTaiManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        XeMayManagement xeMayManagement = null;
        try {
            xeMayManagement = new XeMayManagement();
        } catch (SQLException ex) {
            Logger.getLogger(SelectTransportUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        xeMayManagement.setLocationRelativeTo(null);
        xeMayManagement.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<XeTai> xeTais = (ArrayList<XeTai>) xeTaiController.getXeTaiByHangSanXuat(cboHangSanXuat.getSelectedItem().toString());
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        for (int i = 0; i < xeTais.size(); i++) {
            XeTai xeTai = xeTais.get(i);
            defaultTableModel.addRow(new Object[]{
                i + 1,
                xeTai.getId(),
                "Xe tải",
                xeTai.getHangSanXuat(),
                xeTai.getNamSanXuat(),
                xeTai.getGiaBan(),
                xeTai.getMau(),
                xeTai.getTrongTai()
            });
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArrayList<XeTai> xeTais = (ArrayList<XeTai>) xeTaiController.getXeTaiByMau(cboMau.getSelectedItem().toString());
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        for (int i = 0; i < xeTais.size(); i++) {
            XeTai xeTai = xeTais.get(i);
            defaultTableModel.addRow(new Object[]{
                i + 1,
                xeTai.getId(),
                "Xe tải",
                xeTai.getHangSanXuat(),
                xeTai.getNamSanXuat(),
                xeTai.getGiaBan(),
                xeTai.getMau(),
                xeTai.getTrongTai()
            });
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            UpdateTable();
        } catch (SQLException ex) {
            Logger.getLogger(XeTaiManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ArrayList<XeTai> xeTais = (ArrayList<XeTai>) xeTaiController.getXeTaiByNam(cboNamSanXuat.getSelectedItem().toString());
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        for (int i = 0; i < xeTais.size(); i++) {
            XeTai xeTai = xeTais.get(i);
            defaultTableModel.addRow(new Object[]{
                i + 1,
                xeTai.getId(),
                "Xe tải",
                xeTai.getHangSanXuat(),
                xeTai.getNamSanXuat(),
                xeTai.getGiaBan(),
                xeTai.getMau(),
                xeTai.getTrongTai()
            });
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (txtGiaBan.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Giá bán không được để trống", "Lỗi tìm kiếm", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<XeTai> xeTais = (ArrayList<XeTai>) xeTaiController.getXeTaiByGiaBan(txtGiaBan.getText());
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        for (int i = 0; i < xeTais.size(); i++) {
            XeTai xeTai = xeTais.get(i);
            defaultTableModel.addRow(new Object[]{
                i + 1,
                xeTai.getId(),
                "Xe tải",
                xeTai.getHangSanXuat(),
                xeTai.getNamSanXuat(),
                xeTai.getGiaBan(),
                xeTai.getMau(),
                xeTai.getTrongTai()
            });
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (txtTrongTai.getText().trim().compareTo("") == 0) {
            JOptionPane.showConfirmDialog(null, "Trọng tải không được để trống", "Lỗi tìm kiếm", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<XeTai> xeTais = (ArrayList<XeTai>) xeTaiController.getXeTaiByTrongTai(txtTrongTai.getText());
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }

        for (int i = 0; i < xeTais.size(); i++) {
            XeTai xeTai = xeTais.get(i);
            defaultTableModel.addRow(new Object[]{
                i + 1,
                xeTai.getId(),
                "Xe tải",
                xeTai.getHangSanXuat(),
                xeTai.getNamSanXuat(),
                xeTai.getGiaBan(),
                xeTai.getMau(),
                xeTai.getTrongTai()
            });
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XeTaiManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XeTaiManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XeTaiManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XeTaiManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new XeTaiManagement().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(XeTaiManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private XeTaiController xeTaiController = new XeTaiController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboHangSanXuat;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboNamSanXuat;
    private javax.swing.JComboBox<String> cboSoChoNgoi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhuongTien;
    private javax.swing.JTextField txtCongXuat;
    private javax.swing.JTextField txtDongCo;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTrongTai;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPhuongTien.getModel();
        tblPhuongTien.setModel(defaultTableModel);
        txtId.setEnabled(false);
        txtDongCo.setEnabled(false);
        cboSoChoNgoi.setEnabled(false);
        txtCongXuat.setEnabled(false);
        txtTrongTai.setEnabled(true);

        loadNamSanXuat();
        this.dispose();
        setLocationRelativeTo(null);
    }

    private void loadNamSanXuat() {
        int namHienTai = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = namHienTai; i >= 1920; i--) {
            ((DefaultComboBoxModel) cboNamSanXuat.getModel()).addElement(Integer.toString(i));
        }
    }
}
